[package]
name = "xipr-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "XIPRNET server implementation"

[dependencies]
xipr-core = { path = "../core" }

# Use workspace dependencies where possible
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
uuid.workspace = true
chrono.workspace = true

# Web framework
axum = "0.8.4"
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["cors"] }

# Database
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "chrono"] }
redis = { version = "0.32.5", features = ["tokio-comp"] }

# Async runtime
async-trait = "0.1"

# Error handling
anyhow = "1.0"

# Logging
tracing-subscriber = "0.3"

# Utilities
base64 = "0.22.1"

# Configuration
config = "0.15.15"

[dev-dependencies]
tokio-test = "0.4"
